from dearfy.base.item import Item, ItemKwargs
# > Local Imports
from typing_extensions import Unpack

# ! Container Base Class

class Container(Item):
    _node_children: list[Item]
    
    def __init__(self, **kwargs: Unpack[ItemKwargs]) -> None: ...
    
    def __dearfy_preparing__(self, app: object) -> None: ...
    def __dearfy_preinit__(self) -> None: ...
    def __dearfy_init__(self) -> None: ...
    def __dearfy_postinit__(self) -> None: ...